#!/usr/bin/env python
#Search stack overflow from command line

import argparse
import requests
import json


def search_stack_overflow(query, tagged, min_answers):
    if min_answers == None:
        min_answers = 1

    ## Construct the URL for the API endpoint
    url = "https://api.stackexchange.com/2.3/search/advanced"

    ## Set the params for the GET request

    params = {
        "order": "desc",
        "sort": "relevance",
        "q": query,
        "site": "stackoverflow",
        "tagged": tagged
    }

    ## Send the GET request and get the response
    response = requests.get(url, params=params)

    ## Parse JSON
    data = json.loads(response.text)

    ## TODO: Implement custom sort that prioritizes recent answers
    ## orrrrr have a filter that is always on unless otherwise flagged that limits results to the past 18 months. 

    ## Print the search results (Limit of 5)
    
    for index, item in enumerate(data['items']):
        if index < 6:
            print(f'{item["title"]} - {item["link"]}')

if __name__ == "__main__":
    ## Define the command-line arguments
    parser = argparse.ArgumentParser()
    parser.add_argument("-q", "--query", required=True, help="Content of the query to be submitted.")
    parser.add_argument("-t", "--tagged", required=False, help="Filters posts to those containing the tags supplied")
    parser.add_argument("-a", "--min_answers", required=False, help="The minimum number of answers returned questions must have. Default value of 1")

    args = parser.parse_args()

    search_stack_overflow(args.query, args.tagged, args.min_answers)